### ISSUE TITLE
Choose a storage engine for news articles

### ISSUE THREAD

**Issue by afuetterer** [anfranken/news-scrap#3]
Where do we want to store news articles after scraping?

- [ ] relational database
- [ ] mongodb
- ~elasticsearch~

Something else?

**Comment by anfranken** [comment]
I would prefer a no-SQL database and I think Mongo wold be better than ES because it has a more broader approach. But I don't have any expertise in this field :)

**Comment by afuetterer** [comment]
Let's go with MongoDB then?
